/*
# Create Pinjaman table for member loans

1. New Tables
- `Pinjaman` — records loans made from the mess cash fund to members.
  - `id` (bigint identity PK)
  - `tanggal_pinjam` (date, not null) — the date the loan was given
  - `id_anggota` (bigint, FK to Anggota.id) — who borrowed the money
  - `jumlah` (numeric, not null) — amount borrowed
  - `keterangan` (text, nullable) — description/purpose
  - `status` (text, not null, default 'Belum Lunas') — 'Belum Lunas' or 'Lunas'
  - `created_at` (timestamptz, default now())

2. Security (RLS)
- Enable RLS on Pinjaman.
- All authenticated users can SELECT (members can view the loan table).
- Only admins can INSERT, UPDATE, DELETE. Admin check is via Anggota.role = 'admin'
  for the current user's email matched to Anggota.email.
- Uses auth.uid() and a join to Anggota through auth.users email.

3. Notes
- The admin check uses a subquery: EXISTS (SELECT 1 FROM Anggota a
  WHERE a.email = (SELECT email FROM auth.users WHERE id = auth.uid())
  AND a.role = 'admin').
- This allows admin-only management of loans while all members can see them.
*/

CREATE TABLE IF NOT EXISTS "Pinjaman" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal_pinjam date NOT NULL,
  id_anggota bigint REFERENCES "Anggota"(id) ON DELETE SET NULL,
  jumlah numeric NOT NULL DEFAULT 0,
  keterangan text,
  status text NOT NULL DEFAULT 'Belum Lunas',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE "Pinjaman" ENABLE ROW LEVEL SECURITY;

-- All authenticated users can view loans
DROP POLICY IF EXISTS "select_pinjaman" ON "Pinjaman";
CREATE POLICY "select_pinjaman"
ON "Pinjaman" FOR SELECT
TO authenticated
USING (true);

-- Only admins can insert loans
DROP POLICY IF EXISTS "insert_pinjaman_admin" ON "Pinjaman";
CREATE POLICY "insert_pinjaman_admin"
ON "Pinjaman" FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM "Anggota" a
    WHERE a.email = (SELECT email FROM auth.users WHERE id = auth.uid())
    AND a.role = 'admin'
  )
);

-- Only admins can update loans (e.g. change status to Lunas)
DROP POLICY IF EXISTS "update_pinjaman_admin" ON "Pinjaman";
CREATE POLICY "update_pinjaman_admin"
ON "Pinjaman" FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM "Anggota" a
    WHERE a.email = (SELECT email FROM auth.users WHERE id = auth.uid())
    AND a.role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM "Anggota" a
    WHERE a.email = (SELECT email FROM auth.users WHERE id = auth.uid())
    AND a.role = 'admin'
  )
);

-- Only admins can delete loans
DROP POLICY IF EXISTS "delete_pinjaman_admin" ON "Pinjaman";
CREATE POLICY "delete_pinjaman_admin"
ON "Pinjaman" FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM "Anggota" a
    WHERE a.email = (SELECT email FROM auth.users WHERE id = auth.uid())
    AND a.role = 'admin'
  )
);
